AWSTemplateFormatVersion: 2010-09-09
Description: Deployment of the SlackBot
Transform: AWS::Serverless-2016-10-31

Resources:
  S3DataStore:
    Type: AWS::S3::Bucket
  SlackBotFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../dist/slackBot/slackBot.zip
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 30
      Role: !GetAtt SlackBotRole.Arn
  SlackBotRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        -
          PolicyName: SlackBotAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource:
                  - !Sub "arn:aws:s3:::${S3DataStore}"
                  - !Sub "arn:aws:s3:::${S3DataStore}/*"
  RestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Body:
        info:
          version: '1.0'
          title: !Ref 'AWS::StackName'
        paths:
          /webhook:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SlackBotFunction.Arn}/invocations"
                responses:
                  default:
                    statusCode: 200
                    responseTemplates:
                      application/json: ""
                requestTemplates:
                  application/x-www-form-urlencoded: |-
                    ## From https://gist.github.com/199911/68a43f83fd933b1e3ac6
                    ## convert HTML POST data or HTTP GET query string to JSON

                    ## get the raw post data from the AWS built-in variable and give it a nicer name
                    #if ($context.httpMethod == "POST")
                     #set($rawAPIData = $input.path("$"))
                    #elseif ($context.httpMethod == "GET")
                     #set($rawAPIData = $input.params().querystring)
                     #set($rawAPIData = $rawAPIData.toString())
                     #set($rawAPIDataLength = $rawAPIData.length() - 1)
                     #set($rawAPIData = $rawAPIData.substring(1, $rawAPIDataLength))
                     #set($rawAPIData = $rawAPIData.replace(", ", "&"))
                    #else
                     #set($rawAPIData = "")
                    #end

                    ## first we get the number of "&" in the string, this tells us if there is more than one key value pair
                    #set($countAmpersands = $rawAPIData.length() - $rawAPIData.replace("&", "").length())

                    ## if there are no "&" at all then we have only one key value pair.
                    ## we append an ampersand to the string so that we can tokenise it the same way as multiple kv pairs.
                    ## the "empty" kv pair to the right of the ampersand will be ignored anyway.
                    #if ($countAmpersands == 0)
                     #set($rawPostData = $rawAPIData + "&")
                    #end

                    ## now we tokenise using the ampersand(s)
                    #set($tokenisedAmpersand = $rawAPIData.split("&"))

                    ## we set up a variable to hold the valid key value pairs
                    #set($tokenisedEquals = [])

                    ## now we set up a loop to find the valid key value pairs, which must contain only one "="
                    #foreach( $kvPair in $tokenisedAmpersand )
                     #set($countEquals = $kvPair.length() - $kvPair.replace("=", "").length())
                     #if ($countEquals == 1)
                      #set($kvTokenised = $kvPair.split("="))
                      #if ($kvTokenised[0].length() > 0)
                       ## we found a valid key value pair. add it to the list.
                       #set($devNull = $tokenisedEquals.add($kvPair))
                      #end
                     #end
                    #end

                    ## next we set up our loop inside the output structure "{" and "}"
                    {
                    #foreach( $kvPair in $tokenisedEquals )
                      ## finally we output the JSON for this pair and append a comma if this isn't the last pair
                      #set($kvTokenised = $kvPair.split("="))
                     "$util.urlDecode($kvTokenised[0])" : #if($kvTokenised[1].length() > 0)"$util.urlDecode($kvTokenised[1])"#{else}""#end#if( $foreach.hasNext ),#end
                    #end
                    }
        swagger: '2.0'
  SlackBotFunctionRestApiPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      Principal: apigateway.amazonaws.com
      FunctionName: !Ref SlackBotFunction
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/Prod/POST/webhook"
  Deployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref RestApi
      StageName: Prod
